In [1]:
# Nombre: Cristina Maureira   Rut: 22.356.447-k
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import string
rng = np.random.default_rng(seed=15389)

In [2]:
# usando rng.uniform se crea los arreglos aleatorios entre los intervalos pedidos con el mismo tamaño
R = rng.uniform(low=0.5,high=5,size=(100,)) # los radios estelares
d = rng.uniform(low=50,high=500,size=(100,)) # las distancias
Teff = rng.uniform(low=3000,high=10000,size=(100,)) # y las temperaturas efectivas

In [3]:
identificador = (i for i in range(1,101)) # el indentificador
dict_1 = {"radio_estelar":R,"distancia":d,"temperatura_efectiva":Teff,"identificador":identificador} # se les pone nombre a las columnas
catalogo = pd.DataFrame(dict_1) # se crea el dataFrame
catalogo_10 = catalogo[catalogo["identificador"]<11] # se acorta el dataFrame a los primeros diez valores
catalogo_10

   radio_estelar   distancia  temperatura_efectiva  identificador
0       2.719103  267.161736           8790.227114              1
1       1.256451  498.279486           3777.719552              2
2       4.058192  168.798731           7956.753068              3
3       4.710469   67.530509           4286.912641              4
4       3.014792  133.705737           8317.698674              5
5       4.179849  431.138867           8474.551613              6
6       1.900577   57.159352           9314.127801              7
7       4.708454  344.854980           5748.673381              8
8       0.976615  198.380265           3567.592002              9
9       2.719767   90.253261           9328.475745             10

In [4]:
catalogo_10.describe() # estadisticas descriptivas del dataFrame

       radio_estelar   distancia  temperatura_efectiva  identificador
count      10.000000   10.000000             10.000000       10.00000
mean        3.024427  225.726292           6956.273159        5.50000
std         1.368324  155.147996           2354.191663        3.02765
min         0.976615   57.159352           3567.592002        1.00000
25%         2.105209  101.116380           4652.352826        3.25000
50%         2.867280  183.589498           8137.225871        5.50000
75%         4.149435  325.431669           8711.308239        7.75000
max         4.710469  498.279486           9328.475745       10.00000

In [5]:
def luminosidad(R, Teff):
    """
    Calcula la luminosidad de una estrella con su radio estelar y temperatura efectiva.

    Parameters
    ----------
    R : float
        Radio estelar.
    Teff : float
        Temperatura efectiva.

    Returns
    -------
    float
        La luminosidad solar de la estrella.
    """
    r = R*6.957*(10**8) # de radio estelar a metros
    sigma = 5.67*(10**-8) # constante de Stefan Boltzmann
    L = 4*np.pi*(r**2)*sigma*(Teff**4)
    return L/(3.828*(10**26)) # pasa de vatios a luminosidad solar
"""
aqui cree una lista que pudiera guardar las luminosidades. En el for se fue agregando con append los valores, el bucle los itera
por fila gracias al iloc, se selecciona la primera y tercera columna que son el radio y la temperatura respectivamente para
usar sus floats en la funcion de luminosidad.
"""
L = []
for i in range(10):
    L.append(luminosidad(catalogo_10.iloc[i].values[0],catalogo_10.iloc[i].values[2]))
# se añade al dataFrame
catalogo_10["luminosidad"]=L
catalogo_10

   radio_estelar   distancia  temperatura_efectiva  identificador  luminosidad
0       2.719103  267.161736           8790.227114              1    39.766444
1       1.256451  498.279486           3777.719552              2     0.289651
2       4.058192  168.798731           7956.753068              3    59.466689
3       4.710469   67.530509           4286.912641              4     6.751057
4       3.014792  133.705737           8317.698674              5    39.191552
5       4.179849  431.138867           8474.551613              6    81.180746
6       1.900577   57.159352           9314.127801              7    24.490901
7       4.708454  344.854980           5748.673381              8    21.811831
8       0.976615  198.380265           3567.592002              9     0.139192
9       2.719767   90.253261           9328.475745             10    50.462785

In [6]:
def flujo(d, L):
    """
    Calcula el flujo observado con la luminosidad y distancia de la estrella.

    Parameters
    ----------
    d : float
        distancia [pc].
    L : float
        luminosidad solar de la estrella.

    Returns
    -------
    float
        flujo observado de la estrella [W*(m**-2)].
    """
    D = d*3.0857*(10**16) # parsecs a metros
    l = L*3.828*(10**26) # luminosidad solar a vatios
    F = l/(4*np.pi*(D**2)) # flujo en vatios por metro cuadrado
    return F
# hice lo mismo que con la luminosidad, solo que con la segunda y quinta columna
F = []
for i in range(10):
    F.append(luminosidad(catalogo_10.iloc[i].values[1],catalogo_10.iloc[i].values[4]))
# se añade al dataFrame
catalogo_10["flujo"]=F
catalogo_10

,radio_estelar,distancia,temperatura_efectiva,identificador,luminosidad,flujo
0,2.719103,267.161736,8790.227114,1,39.766444,1.607980e-04
1,1.256451,498.279486,3777.719552,2,0.289651,1.574387e-12
2,4.058192,168.798731,7956.753068,3,59.466689,3.209951e-04
3,4.710469,67.530509,4286.912641,4,6.751057,8.533988e-09
4,3.014792,133.705737,8317.698674,5,39.191552,3.799574e-05
5,4.179849,431.138867,8474.551613,6,81.180746,7.272965e-03
6,1.900577,57.159352,9314.127801,7,24.490901,1.058909e-06
7,4.708454,344.854980,5748.673381,8,21.811831,2.424971e-05
8,0.976615,198.380265,3567.592002,9,0.139192,1.330800e-14
9,2.719767,90.253261,9328.475745,10,50.462785,4.758561e-05

In [7]:
# estrellas de menor y mayor luminosidad
catalogo_10[(catalogo_10["luminosidad"]==(np.min(catalogo_10["luminosidad"])))|(catalogo_10["luminosidad"]==(np.max(catalogo_10["luminosidad"])))]

,radio_estelar,distancia,temperatura_efectiva,identificador,luminosidad,flujo
5,4.179849,431.138867,8474.551613,6,81.180746,7.272965e-03
8,0.976615,198.380265,3567.592002,9,0.139192,1.330800e-14

In [9]:
# estrellas de menor y mayor flujo
catalogo_10[(catalogo_10["flujo"]==(np.min(catalogo_10["flujo"])))|(catalogo_10["flujo"]==(np.max(catalogo_10["flujo"])))]

,radio_estelar,distancia,temperatura_efectiva,identificador,luminosidad,flujo
5,4.179849,431.138867,8474.551613,6,81.180746,7.272965e-03
8,0.976615,198.380265,3567.592002,9,0.139192,1.330800e-14